platform :osx, '10.12'

use_frameworks!

def shared_pods
  pod 'Sparkle'
end

target 'MacForge' do
  shared_pods

  # Basics
  pod 'AppCenter'
  pod 'EDStarRating'
  pod 'LetsMove'
  pod 'SDWebImage'

  # Firebase
  # pod 'FirebaseABTesting'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'
  pod 'FirebaseFirestore'
  # pod 'FirebaseFunctions'
  # pod 'FirebaseMessaging'
  # pod 'FirebaseRemoteConfig'
  pod 'FirebaseStorage'
  
  # pod 'FirebaseCore', :path => './firebase_sdk/'
  # pod 'FirebaseDatabase', :path => './firebase_sdk/'
  # pod 'FirebaseStorage', :path => './firebase_sdk/'
  # pod 'FirebaseAuth', :path => './firebase_sdk/'
  # pod 'FirebaseFirestore', :path => './firebase_sdk/'
end

target 'purchaseValidationApp' do
  pod 'PaddleV4'
end

target 'MacForgeHelper' do
  shared_pods
end

target 'com.w0lf.MacForge.Injector' do
end

target 'com.w0lf.MacForge.Installer' do
end

target 'MacForgeDockTile' do
end

target 'MacForgeFix' do
end

target 'MacForgeKit' do
end
