platform :osx, '10.13'

use_frameworks!

target 'MacForge' do
  # Basics
  pod 'AppCenter'
  pod 'EDStarRating'
  pod 'LetsMove'
  pod 'PaddleV4'
  pod 'SDWebImage'
  pod 'Sparkle'

  # Firebase
  pod 'FirebaseAuth'
  # pod 'FirebaseABTesting'
  # pod 'FirebaseDatabase'
  # pod 'FirebaseFirestore'
  # pod 'FirebaseFunctions'
  # pod 'FirebaseMessaging'
  # pod 'FirebaseRemoteConfig'
  # pod 'FirebaseStorage'
end

target 'MacForgeHelper' do
  pod 'Sparkle'
end

target 'com.macenhance.MacForge.Injector' do
end

target 'MacForgeDockTile' do
end